### PR TITLE
spaces for that ａｅｓｔｈｅｔｉｃ

### PR DESCRIPTION
**Pull request by dog-song**
yes it fucks up the tabbing, you can kick my ass later

### CODE REVIEW

**Comment by xmatmen** [comment]
the tabbing is literally defined in the eslint config you twat

**Comment by dog-song** [comment]
kill yourself

**Comment by xmatmen** [comment]
image
what a tragedy

**Comment by dog-song** [comment]
I'm making pointless pull requests to show that I'm doing something

**Comment by xmatmen** [comment]
yeah thats nice and all but jslint is gonna scream at me for doing this

**Comment by dog-song** [comment]
rekt

**Pull request closed without merging**
